# Generated by Django 5.2.6 on 2025-09-10 05:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_customuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('item_name', models.CharField(max_length=200)),
                ('food_type', models.CharField(choices=[('Cooked Meals', 'Cooked Meals'), ('Bakery', 'Bakery'), ('Produce', 'Produce'), ('Dairy', 'Dairy'), ('Packaged', 'Packaged')], max_length=50)),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('unit', models.CharField(choices=[('portions', 'Portions'), ('kg', 'kg'), ('loaves', 'Loaves'), ('litres', 'Litres'), ('packs', 'Packs')], max_length=20)),
                ('pickup_location', models.TextField()),
                ('date_available', models.DateField()),
                ('time_available', models.TimeField()),
                ('food_image', models.ImageField(blank=True, null=True, upload_to='donations/food/')),
                ('packaging_image', models.ImageField(blank=True, null=True, upload_to='donations/packaging/')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('expired', 'Expired'), ('reserved', 'Reserved')], default='pending', max_length=20)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='donations/qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zerobite_donations',
                'ordering': ['-created_at'],
            },
        ),
    ]
